### PR TITLE
Add model export functionality to pip package

### PR DESCRIPTION
**Pull request by spal-synaptics**
- Moved model export and adjacent functionality to `pysynap` namespace as a new module `tools`
- New script `export_yolo.py` that exports YOLOv8, v9, and v11 models directly to synap (`synap_convert` failes with yolov10)
- New entry points:
   - `synap_export_yolo`: Exports supported YOLO models to synap
   - `synap_expot_clean`: Cleans up model export files and cache
   - `synap_copy`: Copies synap models to board via ADB or SSH
   - `synap_profile`: Profiles synap models on board (via `syanp_cli`), requires board connected via ADB/SSH

Pip package tested working on Ubuntu 22.04 LTS running on WSL2

Usage example:

```bash
synap_export_yolo \
--models yolov8n-seg yolov9t yolo11n-pose \
--target SL1680 \
--quant_types float16 uint8 \
--quant_dataset "path/to/dataset/*.jpg"
```

This should generate 6 tflite models (3 models * 2 quant types) and their corresponding YAMLs in `models/exported`, and the converted synap models in `models/converted`, which can then be transferred to a connected board with `synap_copy `

### CODE REVIEW

**Review by mdenna-synaptics — COMMENTED** [review]
Looks very good to me!
One minor thing we found nice in other scripts that require connection to the board is to check for board availability at the beginning instead of crashing if not available, for example https://github.com/syna-astra-dev/synap-models/blob/84e43d48db2a6f663db6e9badb0881c1ca34aaf9/synap_test.py#L756 in case you want to do something similar. What do you think?

**Comment by spal-synaptics** [comment]
> Looks very good to me! One minor thing we found nice in other scripts that require connection to the board is to check for board availability at the beginning instead of crashing if not available, for example https://github.com/syna-astra-dev/synap-models/blob/84e43d48db2a6f663db6e9badb0881c1ca34aaf9/synap_test.py#L756 in case you want to do something similar. What do you think?

Good idea, done! [b12f2ef](https://github.com/synaptics-synap/toolkit/pull/11/commits/b12f2ef9233d336dd35c5a2e8a368c14e4c54820)

**Review by Meet-synaptics — APPROVED** [review]
Looks good to me!

**Comment by dpajak-synaptics** [comment]
[celebrate]     Dominic Pajak reacted to your message:
________________________________

**Review by mdenna-synaptics — APPROVED** [review]

**Review by mdenna-synaptics — APPROVED** [review]

**Comment by dpajak-synaptics** [comment]
This is great! Let’s make sure people know it exists!

Please could you create a developer tutorial for exporting from Yolo with this @Sauryadeep ***@***.***>?

Could I also request you add YOLO11 (I think same format) so we don’t look out-of-date …

Then we can feature on the main page - there is already a place holder :)


***@***.***

From: mdenna-synaptics ***@***.***>
Date: Friday, November 22, 2024 at 12:18 AM
To: synaptics-synap/toolkit ***@***.***>
Cc: Dominic Pajak ***@***.***>, Review requested ***@***.***>
Subject: Re: [synaptics-synap/toolkit] Add model export functionality to pip package (PR #11)
CAUTION: Email originated externally, do not click links or open attachments unless you recognize the sender and know the content is safe.


@mdenna-synaptics approved this pull request.

**Review by ayounes-synaptics — APPROVED** [review]

**Pull request merged**
